on: push
name: Build and deploy on push
jobs:
  yarnInstall:
    name: yarn install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn build
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master
        FOLDER: public
