on: push
name: Build and deploy on push
jobs:
  yarnInstall:
    name: yarn install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: yarn install
      uses: Borales/actions-yarn@master
      with:
        args: install
    - name: yarn build
      uses: Borales/actions-yarn@master
      with:
        args: build
    - name: Filters for GitHub Actions
      uses: actions/bin/filter@3c0b4f0e63ea54ea5df2914b4fabf383368cd0da
      with:
        args: branch hexo
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master
        FOLDER: public
